spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update

  h2:
    console.enabled: true


logging:
  file:
    name: app.log
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.vijayforvictory.demo.jpa: DEBUG
    com.vijayforvictory.demo.jpa.controller: DEBUG
    com.vijayforvictory.demo.jpa.service: DEBUG